name: jaytech-external-oas-openai-v1

on:
  push:
    paths:
      - 'src/openai/openai-api-v1.yaml'
      - '.github/workflows/jaytech-external-oas-openai-v1.yml'

jobs:
  contract-workflow:
    uses: JayTechHQ/jaytech-workflows/.github/workflows/oas-release-contract.yml@master
    with:
      namespace: JayTech.External.OAS.OpenAI.V1
      dotnet-version: "9.x"
      oas-file-path: src/openai/openai-api-v1.yaml
    secrets:
      azure-api-key: ${{ secrets.AZURE_API_KEY }}
      azure-feed: jaytech-nuget
      azure-source: https://pkgs.dev.azure.com/JayTechIT/JayTech/_packaging/jaytech-nuget/nuget/v3/index.json
      pat-github: ${{ secrets.PAT_GITHUB }}